version: '3'

services:
 rabbitmq1:
  image: rabbitmq:3-management
  container_name: rabbitmq1
  hostname: rabbitmq1
  environment:
    - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
  ports:
    - 5673:5672
    - 15673:15672
  volumes:
    - $PWD/storage/rabbitmq1:/var/lib/rabbitmq

 rabbitmq2:
  image: rabbitmq:3-management
  container_name: rabbitmq2
  hostname: rabbitmq2
  entrypoint: /usr/local/bin/cluster-entrypoint.sh
  ports:
    - 5674:5672
    - 15674:15672
  environment:
    - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
  depends_on:
    - rabbitmq1
  volumes:
    - $PWD/storage/rabbitmq2:/var/lib/rabbitmq
    - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh

 rabbitmq3:
  image: rabbitmq:3-management
  container_name: rabbitmq3
  hostname: rabbitmq3
  entrypoint: /usr/local/bin/cluster-entrypoint.sh
  ports:
    - 5675:5672
    - 15675:15672
  environment:
    - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
  depends_on:
    - rabbitmq1
  volumes:
    - $PWD/storage/rabbitmq3:/var/lib/rabbitmq
    - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh

 haproxy:
  image: haproxy:local
  container_name: haproxy
  hostname: haproxy
  ports:
    - 15672:15672
    - 5672:5672
    - 1936:1936
